apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-shop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices-shop-frontend
  template:
    metadata:
      labels:
        app: microservices-shop-frontend
    spec:
      containers:
        - name: microservices-shop-frontend
          image: veangeance00/microservices-shop-frontend:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: microservices-shop-frontend
spec:
  selector:
    app: microservices-shop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80